/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etmswing;

import static etmswing.MainETM.empsList;
import static etmswing.MainETM.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class DisplayData extends javax.swing.JFrame {

    /**
     * Creates new form DisplayData
     */
    String Key;
    String Name;
    public DisplayData(String PassedEmail,String PassedName) {
        Key=PassedEmail;
        Name=PassedName;
        initComponents();
        Image icon=new ImageIcon(this.getClass().getResource(Formicon)).getImage();
        this.setIconImage(icon);
        setResizable(false); // to stop big the form
        EmployeeTableData.getTableHeader().setFont(new Font("Segoe UI",Font.PLAIN,14));
        EmployeeTableData.getTableHeader().setOpaque(false);
        EmployeeTableData.getTableHeader().setBackground(new Color(51,51,51));
        EmployeeTableData.getTableHeader().setForeground(new Color(204,204,204));
        dataFinished.getTableHeader().setFont(new Font("Segoe UI",Font.PLAIN,14));
        dataFinished.getTableHeader().setOpaque(false);
        dataFinished.getTableHeader().setBackground(new Color(51,51,51));
        dataFinished.getTableHeader().setForeground(new Color(204,204,204));
        DisplaySelected();
       
    }
    private  void DisplaySelected(){
        email_val.setText("  "+ Key);//Display Selected EMP Email
        name_val.setText("  " + Name);//Display Selected EMP Name
        DefaultTableModel tblModel=(DefaultTableModel)EmployeeTableData.getModel();
        DefaultTableModel tb2Model=(DefaultTableModel)dataFinished.getModel();
        tblModel.getDataVector().removeAllElements();//for delete old data
        if(!empsList.get(Key).list.isEmpty()){
            for (int i = 0; i < empsList.get(Key).list.size(); i++) {

                String[] displayEmployeesData={empsList.get(Key).list.get(i).title,
                    Integer.toString(empsList.get(Key).list.get(i).priority),
                    empsList.get(Key).list.get(i).assignedDate.toString(),
                    empsList.get(Key).list.get(i).endDate.toString(),
                    empsList.get(Key).list.get(i).description};

                tblModel.addRow(displayEmployeesData);

            }
        }
        if(!empsList.get(Key).Finished_List.isEmpty()){
            for (int i = 0; i < empsList.get(Key).Finished_List.size(); i++) {

                String[] displayEmployeesData={empsList.get(Key).Finished_List.get(i).title,
                    Integer.toString(empsList.get(Key).Finished_List.get(i).priority),
                    empsList.get(Key).Finished_List.get(i).assignedDate.toString(),
                    empsList.get(Key).Finished_List.get(i).endDate.toString(),
                    empsList.get(Key).Finished_List.get(i).description};

                tb2Model.addRow(displayEmployeesData);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        EmpData = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeTableData = new javax.swing.JTable();
        email_lbl = new javax.swing.JLabel();
        email_val = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        name_val = new javax.swing.JLabel();
        empData_title = new javax.swing.JLabel();
        EmpDataFinished = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataFinished = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DisplayData");
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1070, 600));
        setMinimumSize(new java.awt.Dimension(1070, 600));
        setResizable(false);

        Back.setBackground(new java.awt.Color(51, 51, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(204, 204, 204));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        Back.setText("Back To Dashboard");
        Back.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        Back.setFocusPainted(false);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        EmpData.setBackground(getBackground());

        EmployeeTableData.setEnabled(false);
        EmployeeTableData.setAutoCreateRowSorter(true);
        EmployeeTableData.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        EmployeeTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Title", "Task Priorty", "Assigned Date", "End Date", "Task Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTableData.setFillsViewportHeight(true);
        EmployeeTableData.setFocusable(false);
        EmployeeTableData.setGridColor(new java.awt.Color(51, 51, 51));
        EmployeeTableData.setIntercellSpacing(new java.awt.Dimension(0, 0));
        EmployeeTableData.setRowHeight(25);
        EmployeeTableData.setSelectionBackground(new java.awt.Color(102, 102, 102));
        EmployeeTableData.setSelectionForeground(new java.awt.Color(204, 204, 204));
        EmployeeTableData.setShowVerticalLines(false);
        EmployeeTableData.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(EmployeeTableData);
        if (EmployeeTableData.getColumnModel().getColumnCount() > 0) {
            EmployeeTableData.getColumnModel().getColumn(0).setMinWidth(150);
            EmployeeTableData.getColumnModel().getColumn(0).setPreferredWidth(150);
            EmployeeTableData.getColumnModel().getColumn(0).setMaxWidth(150);
            EmployeeTableData.getColumnModel().getColumn(1).setMinWidth(100);
            EmployeeTableData.getColumnModel().getColumn(1).setPreferredWidth(100);
            EmployeeTableData.getColumnModel().getColumn(1).setMaxWidth(100);
            EmployeeTableData.getColumnModel().getColumn(2).setMinWidth(100);
            EmployeeTableData.getColumnModel().getColumn(2).setPreferredWidth(100);
            EmployeeTableData.getColumnModel().getColumn(2).setMaxWidth(100);
            EmployeeTableData.getColumnModel().getColumn(3).setMinWidth(100);
            EmployeeTableData.getColumnModel().getColumn(3).setPreferredWidth(100);
            EmployeeTableData.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        javax.swing.GroupLayout EmpDataLayout = new javax.swing.GroupLayout(EmpData);
        EmpData.setLayout(EmpDataLayout);
        EmpDataLayout.setHorizontalGroup(
            EmpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        EmpDataLayout.setVerticalGroup(
            EmpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );

        email_lbl.setBackground(new java.awt.Color(102, 102, 102));
        email_lbl.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(204, 204, 204));
        email_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl.setText("Email : ");

        email_val.setBackground(new java.awt.Color(80, 80, 80));
        email_val.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        email_val.setForeground(new java.awt.Color(204, 204, 204));
        email_val.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        email_val.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        email_val.setOpaque(true);

        name_lbl.setFont(email_lbl.getFont());
        name_lbl.setForeground(new java.awt.Color(204, 204, 204));
        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl.setText("Name : ");

        name_val.setBackground(new java.awt.Color(80, 80, 80));
        name_val.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        name_val.setForeground(new java.awt.Color(204, 204, 204));
        name_val.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name_val.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        name_val.setOpaque(true);

        empData_title.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        empData_title.setForeground(new java.awt.Color(204, 204, 204));
        empData_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empData_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list_view_40.png"))); // NOI18N
        empData_title.setText("Employee Data And Tasks");

        dataFinished.setAutoCreateRowSorter(true);
        dataFinished.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dataFinished.setForeground(new java.awt.Color(0, 153, 0));
        dataFinished.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Title", "Task Priority", "Assign Date", "End Date", "Task Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataFinished.setFillsViewportHeight(true);
        dataFinished.setFocusable(false);
        dataFinished.setGridColor(new java.awt.Color(51, 51, 51));
        dataFinished.setIntercellSpacing(new java.awt.Dimension(0, 0));
        dataFinished.setRowHeight(25);
        dataFinished.setRowSelectionAllowed(false);
        dataFinished.setSelectionBackground(new java.awt.Color(102, 102, 102));
        dataFinished.setSelectionForeground(new java.awt.Color(204, 204, 204));
        dataFinished.setShowVerticalLines(false);
        dataFinished.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(dataFinished);
        if (dataFinished.getColumnModel().getColumnCount() > 0) {
            dataFinished.getColumnModel().getColumn(0).setMinWidth(150);
            dataFinished.getColumnModel().getColumn(0).setPreferredWidth(150);
            dataFinished.getColumnModel().getColumn(0).setMaxWidth(150);
            dataFinished.getColumnModel().getColumn(1).setMinWidth(100);
            dataFinished.getColumnModel().getColumn(1).setPreferredWidth(100);
            dataFinished.getColumnModel().getColumn(1).setMaxWidth(100);
            dataFinished.getColumnModel().getColumn(2).setMinWidth(100);
            dataFinished.getColumnModel().getColumn(2).setPreferredWidth(100);
            dataFinished.getColumnModel().getColumn(2).setMaxWidth(100);
            dataFinished.getColumnModel().getColumn(3).setMinWidth(100);
            dataFinished.getColumnModel().getColumn(3).setPreferredWidth(100);
            dataFinished.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout EmpDataFinishedLayout = new javax.swing.GroupLayout(EmpDataFinished);
        EmpDataFinished.setLayout(EmpDataFinishedLayout);
        EmpDataFinishedLayout.setHorizontalGroup(
            EmpDataFinishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(EmpDataFinishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmpDataFinishedLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        EmpDataFinishedLayout.setVerticalGroup(
            EmpDataFinishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
            .addGroup(EmpDataFinishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1070, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(1070, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(1070, 600));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tick_ok.png"))); // NOI18N
        jLabel2.setText("Finished Tasks List : ");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Displaybtn.png"))); // NOI18N
        jLabel3.setText("Remained Tasks List : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpDataFinished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empData_title, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email_val, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_val, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empData_title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(email_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email_val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpDataFinished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         ManagerForm BackManagerForm=new ManagerForm(); //call new form
       BackManagerForm.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        // TODO add your handling code here:
        setHoverColor(Back);
        dashboardbtn_over = true;
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        // TODO add your handling code here:
        setResetColor(Back);
       dashboardbtn_over = false;
    }//GEN-LAST:event_BackMouseExited

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        // TODO add your handling code here:
        setPressColor(Back);
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
        // TODO add your handling code here:
              if (dashboardbtn_over) {
        setHoverColor(Back);
        } else {
        setResetColor(Back);
        }
    }//GEN-LAST:event_BackMouseReleased
    private void setPressColor(javax.swing.JButton b) {
            b.setBackground(new Color(153, 153, 153));
    }
    private void setHoverColor(javax.swing.JButton b) {
            b.setBackground(new Color(102, 102, 102));
    }
    private void setResetColor(javax.swing.JButton b) {
            b.setBackground(new Color(51, 51, 51));
    }
    private boolean dashboardbtn_over;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayData(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel EmpData;
    private javax.swing.JPanel EmpDataFinished;
    private javax.swing.JTable EmployeeTableData;
    private javax.swing.JTable dataFinished;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel email_val;
    private javax.swing.JLabel empData_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel name_val;
    // End of variables declaration//GEN-END:variables
}
