/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etmswing;

import static etmswing.MainETM.Formicon;
import static etmswing.MainETM.empsList;
import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import javax.swing.ImageIcon;

/**
 *
 * @author omar3
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    int mousePX;
    int mousePY;
    public LoginForm() {
        initComponents();
        Image icon=new ImageIcon(this.getClass().getResource(Formicon)).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        password_lb = new javax.swing.JLabel();
        email_lb = new javax.swing.JLabel();
        username_tx = new javax.swing.JTextField();
        password_tx = new javax.swing.JPasswordField();
        exit_btn = new javax.swing.JButton();
        login_btn = new javax.swing.JButton();
        user_icon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eye_disable = new javax.swing.JLabel();
        eye_show = new javax.swing.JLabel();
        password_error_message = new javax.swing.JLabel();
        email_error_message = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(907, 675));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(907, 675));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        login_title.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 48)); // NOI18N
        login_title.setForeground(new java.awt.Color(204, 204, 204));
        login_title.setText("Log in");
        login_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        password_lb.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        password_lb.setForeground(new java.awt.Color(204, 204, 204));
        password_lb.setText("Password");

        email_lb.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        email_lb.setForeground(new java.awt.Color(204, 204, 204));
        email_lb.setText("Email");

        username_tx.setBackground(new java.awt.Color(51, 51, 55));
        username_tx.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        username_tx.setForeground(new java.awt.Color(204, 204, 204));
        username_tx.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        password_tx.setBackground(new java.awt.Color(51, 51, 55));
        password_tx.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        password_tx.setForeground(new java.awt.Color(204, 204, 204));
        password_tx.setBorder(username_tx.getBorder());

        exit_btn.setBackground(new java.awt.Color(51, 51, 51));
        exit_btn.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(204, 204, 204));
        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_exit.png"))); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit_btn.setFocusPainted(false);
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exit_btnMouseReleased(evt);
            }
        });
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        login_btn.setBackground(new java.awt.Color(51, 51, 51));
        login_btn.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        login_btn.setForeground(new java.awt.Color(204, 204, 204));
        login_btn.setText("Login");
        login_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_btn.setFocusPainted(false);
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                login_btnMouseReleased(evt);
            }
        });
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        user_icon.setForeground(new java.awt.Color(204, 204, 204));
        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_icon.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        eye_disable.setBackground(new java.awt.Color(51, 51, 51));
        eye_disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye_disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye_invisible.png"))); // NOI18N
        eye_disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_disableMouseClicked(evt);
            }
        });

        eye_show.setBackground(new java.awt.Color(51, 51, 51));
        eye_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye_visible.png"))); // NOI18N
        eye_show.setLabelFor(jPanel1);
        eye_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_showMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eye_show, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(eye_disable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eye_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eye_disable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        password_error_message.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        password_error_message.setForeground(new java.awt.Color(185, 63, 63));

        email_error_message.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        email_error_message.setForeground(new java.awt.Color(185, 63, 63));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(login_title))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_tx)
                            .addComponent(password_lb)
                            .addComponent(email_lb)
                            .addComponent(password_tx)
                            .addComponent(password_error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(user_icon)
                                .addGap(12, 12, 12)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(login_title)
                .addGap(34, 34, 34)
                .addComponent(email_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(password_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 450, 680));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Employee Task Manager Application");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 390, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogInForm.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(472, 675));
        jLabel1.setPreferredSize(new java.awt.Dimension(472, 675));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-990, -180, 1500, 1630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(30);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        email_error_message.setText("");
        password_error_message.setText("");
        String input_username = username_tx.getText();
        String input_password = String.valueOf(password_tx.getPassword());
        if(input_username.equals("") || input_password.equals(""))
        {
            if (input_username.equals("")) {
                email_error_message.setText("Email field is required");
            }
            if (input_password.equals("")) {
                password_error_message.setText("Password field is required");
            }
        }
        ///Admin log in
        else if(input_username.equals("a")&& input_password.equals("1"))
        {
            ManagerForm e = new ManagerForm();
            e.setVisible(true);
            this.setVisible(false);
        }
        ///User log in
        else if(empsList.get(input_username) != null && input_password.equals(empsList.get(input_username).password))
        {
            EmployeeForm e = new EmployeeForm(empsList.get(input_username));
            e.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            password_error_message.setText("Invalid Password");
            email_error_message.setText("Invalid Email");
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void eye_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_showMouseClicked
        password_tx.setEchoChar((char)8226);
        eye_disable.setVisible(true);
        eye_disable.setEnabled(true);
        eye_show.setVisible(false);
        eye_show.setEnabled(false);
    }//GEN-LAST:event_eye_showMouseClicked

    private void eye_disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_disableMouseClicked
        password_tx.setEchoChar((char)0);
        eye_disable.setVisible(false);
        eye_disable.setEnabled(false);
        eye_show.setVisible(true);
        eye_show.setEnabled(true);
    }//GEN-LAST:event_eye_disableMouseClicked

    private void login_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseEntered
        setHoverColor(login_btn);
        login_over = true;
    }//GEN-LAST:event_login_btnMouseEntered

    private void login_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseExited
        setResetColor(login_btn);
        login_over = false;
    }//GEN-LAST:event_login_btnMouseExited

    private void exit_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseEntered
        setHoverColor(exit_btn);
        exit_over = true;
    }//GEN-LAST:event_exit_btnMouseEntered

    private void exit_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseExited
        setResetColor(exit_btn);
        exit_over = false;
    }//GEN-LAST:event_exit_btnMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int cordinateX = evt.getXOnScreen();
        int cordinateY = evt.getYOnScreen();
        this.setLocation(cordinateX-mousePX, cordinateY-mousePY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void login_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMousePressed
        setPressColor(login_btn);
    }//GEN-LAST:event_login_btnMousePressed

    private void login_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseReleased
        if (login_over) {
            setHoverColor(login_btn); 
        }
        else{
            setResetColor(login_btn);
        }
    }//GEN-LAST:event_login_btnMouseReleased

    private void exit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMousePressed
        setPressColor(exit_btn);
    }//GEN-LAST:event_exit_btnMousePressed

    private void exit_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseReleased
        if (exit_over) {
            setHoverColor(exit_btn);        
        }
        else{
            setResetColor(exit_btn);
        }
    }//GEN-LAST:event_exit_btnMouseReleased

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        setClickColor(login_btn);
    }//GEN-LAST:event_login_btnMouseClicked

    private void setClickColor(javax.swing.JButton b)
    {
        b.setBackground(new Color(204,204,204));
    }
    private void setPressColor(javax.swing.JButton b)
    {
        b.setBackground(new Color(153,153,153));
    }
    private void setHoverColor(javax.swing.JButton b)
    {
        b.setBackground(new Color(102,102,102));
    }
    private void setResetColor(javax.swing.JButton b)
    {
        b.setBackground(new Color(51,51,51));
    }
    private void setHoverColorBlue(javax.swing.JButton b)
    {
        b.setBackground(new Color(0,0,230));
    }
    /**
     * @param args the command line arguments
     */
    private boolean login_over;
    private boolean exit_over;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_error_message;
    private javax.swing.JLabel email_lb;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel eye_disable;
    private javax.swing.JLabel eye_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel login_title;
    private javax.swing.JLabel password_error_message;
    private javax.swing.JLabel password_lb;
    private javax.swing.JPasswordField password_tx;
    private javax.swing.JLabel user_icon;
    private javax.swing.JTextField username_tx;
    // End of variables declaration//GEN-END:variables
}
