/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etmswing;

//import static com.sun.tools.javac.main.Option.G;
import static etmswing.MainETM.Formicon;
import static etmswing.MainETM.empsList;
import static etmswing.MainETM.postponedTasksList;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omar3
 */
public class ManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerForm
     */
    String Key=null;
    String Name=null;
    int row=-1;
    DefaultTableModel tblModel;
    public ManagerForm() {
        initComponents();
        data.getTableHeader().setFont(new Font("Franklin Gothlic Meduim Cond",Font.PLAIN,18));
        data.getTableHeader().setOpaque(false);
        data.getTableHeader().setBackground(new Color(51, 51, 51));
        data.getTableHeader().setForeground(new Color(204, 204, 204));
        setResizable(false);
        data.getTableHeader().setBackground(new Color(51,51,51));
        data.getTableHeader().setForeground(new Color(204,204,204));
        Image icon=new ImageIcon(this.getClass().getResource(Formicon)).getImage();
        this.setIconImage(icon);
        tblModel=(DefaultTableModel)data.getModel();
        for (String key : empsList.keySet()) {
           String[] displayEmployeesData={empsList.get(key).name,key}; 
           tblModel.addRow(displayEmployeesData);
        }
        if (!postponedTasksList.isEmpty()) {
            approveTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification (2).png")));
            approveTask.setToolTipText("Waiting Tasks to approve");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JButton();
        AddEMP = new javax.swing.JButton();
        Displaybtn = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        AddTask = new javax.swing.JButton();
        DeleteEmp = new javax.swing.JButton();
        Display = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        approveTask = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminForm");
        setBackground(new java.awt.Color(51, 51, 51));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1070, 600));
        setMinimumSize(new java.awt.Dimension(1070, 600));
        setPreferredSize(new java.awt.Dimension(1070, 600));
        setResizable(false);

        Login.setBackground(new java.awt.Color(51, 51, 51));
        Login.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(204, 204, 204));
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        Login.setText("Back To Login");
        Login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        Login.setFocusPainted(false);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginMouseReleased(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        AddEMP.setBackground(new java.awt.Color(51, 51, 51));
        AddEMP.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AddEMP.setForeground(new java.awt.Color(204, 204, 204));
        AddEMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Addbtn.png"))); // NOI18N
        AddEMP.setText("Add Employee");
        AddEMP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        AddEMP.setFocusPainted(false);
        AddEMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddEMPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddEMPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddEMPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddEMPMouseReleased(evt);
            }
        });
        AddEMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEMPActionPerformed(evt);
            }
        });

        Displaybtn.setBackground(new java.awt.Color(51, 51, 51));
        Displaybtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Displaybtn.setForeground(new java.awt.Color(204, 204, 204));
        Displaybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Displaybtn.png"))); // NOI18N
        Displaybtn.setText("Display");
        Displaybtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        Displaybtn.setFocusPainted(false);
        Displaybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DisplaybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisplaybtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisplaybtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DisplaybtnMouseReleased(evt);
            }
        });
        Displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybtnActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(51, 51, 51));
        Update.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Updatebtn.png"))); // NOI18N
        Update.setText(" Update");
        Update.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        Update.setFocusPainted(false);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UpdateMouseReleased(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        AddTask.setBackground(new java.awt.Color(51, 51, 51));
        AddTask.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AddTask.setForeground(new java.awt.Color(204, 204, 204));
        AddTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Addbtn.png"))); // NOI18N
        AddTask.setText("Assign Task");
        AddTask.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        AddTask.setFocusPainted(false);
        AddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddTaskMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddTaskMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddTaskMouseReleased(evt);
            }
        });
        AddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskActionPerformed(evt);
            }
        });

        DeleteEmp.setBackground(new java.awt.Color(51, 51, 51));
        DeleteEmp.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        DeleteEmp.setForeground(new java.awt.Color(204, 204, 204));
        DeleteEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_24.png"))); // NOI18N
        DeleteEmp.setText("Delete Employee");
        DeleteEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        DeleteEmp.setFocusPainted(false);
        DeleteEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteEmpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DeleteEmpMouseReleased(evt);
            }
        });
        DeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmpActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(51, 51, 51));
        Display.setForeground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        data.setBackground(new java.awt.Color(102, 102, 102));
        data.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        data.setForeground(new java.awt.Color(204, 204, 204));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeName", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data.setGridColor(new java.awt.Color(51, 51, 51));
        data.setRowHeight(25);
        data.setSelectionBackground(new java.awt.Color(51, 51, 51));
        data.setSelectionForeground(new java.awt.Color(204, 204, 204));
        data.setShowVerticalLines(false);
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
        Display.setLayout(DisplayLayout);
        DisplayLayout.setHorizontalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DisplayLayout.setVerticalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manager_36.png"))); // NOI18N
        jLabel2.setText("Manager Dashboard");

        approveTask.setBackground(new java.awt.Color(51, 51, 51));
        approveTask.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        approveTask.setForeground(new java.awt.Color(204, 204, 204));
        approveTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification (1).png"))); // NOI18N
        approveTask.setText("Requested Postponed Tasks");
        approveTask.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        approveTask.setFocusPainted(false);
        approveTask.setMaximumSize(new java.awt.Dimension(70, 26));
        approveTask.setMinimumSize(new java.awt.Dimension(70, 26));
        approveTask.setPreferredSize(new java.awt.Dimension(70, 26));
        approveTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approveTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approveTaskMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                approveTaskMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                approveTaskMouseReleased(evt);
            }
        });
        approveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveTaskActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list_24.png"))); // NOI18N
        jLabel3.setText("Employee List");
        jLabel3.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1070, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(1070, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(1070, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Displaybtn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(AddEMP, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(AddTask, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(approveTask, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(DeleteEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(approveTask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Displaybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddEMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEMPActionPerformed
        // TODO add your handling code here:
        AddEmp Add=new AddEmp(); //call new form
       Add.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_AddEMPActionPerformed

    private void DisplaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybtnActionPerformed
        // TODO add your handling code here:
        if(Key==null){  
            JOptionPane.showMessageDialog(this, "Select Employee To Display His Tasks","Error",JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/icons/close_30_decline.png")));
        }
        else if(empsList.get(Key).list.isEmpty() && empsList.get(Key).Finished_List.isEmpty()){
            JOptionPane.showMessageDialog(this, "Selected Employee Doesn’t Have Any Tasks","No Data",JOptionPane.INFORMATION_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/icons/warning_30.png")));
        }
        else{
            DisplayData Display=new DisplayData(Key,Name); //call new form
            Display.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_DisplaybtnActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if(Key==null){  
            JOptionPane.showMessageDialog(this, "Select Employee To Update His Tasks","Error",JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/icons/close_30_decline.png")));
        }
        else if(empsList.get(Key).list.isEmpty()){
             JOptionPane.showMessageDialog(this, "Selected Employee Doesn’t Have Any Tasks","No Data",JOptionPane.INFORMATION_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/icons/information_30.png")));
        }       
        else{
            EditTask Update=new EditTask(Key); //call new form
            Update.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskActionPerformed
        // TODO add your handling code here:
        if(Key==null){  
            JOptionPane.showMessageDialog(this, "Select Employee To Assign Tasks","Error",JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/icons/close_30_decline.png")));
        }
        else{
            AssignTask assignTask=new AssignTask(Key); //call new form & send selected Emp
            assignTask.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_AddTaskActionPerformed

    private void dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMousePressed
        // TODO add your handling code here:
        ///// -> To get data selected
         row= data.getSelectedRow();//Get Selected Row
         Key= data.getModel().getValueAt(row, 1).toString();//Get the Selected EMP Email
         Name= data.getModel().getValueAt(row, 0).toString();//Get the Selected EMP Name
    }//GEN-LAST:event_dataMousePressed
    /////////////////////////////////////////////////////////////////////////
    
    // Display btn actions
    private void DisplaybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplaybtnMouseEntered
        // TODO add your handling code here:
        setHoverColor(Displaybtn);
        displaybtn_over = true;
    }//GEN-LAST:event_DisplaybtnMouseEntered

    private void DisplaybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplaybtnMouseExited
        // TODO add your handling code here:
        setResetColor(Displaybtn);
        displaybtn_over = false;
    }//GEN-LAST:event_DisplaybtnMouseExited

    private void DisplaybtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplaybtnMousePressed
        // TODO add your handling code here:
        setPressColor(Displaybtn);
    }//GEN-LAST:event_DisplaybtnMousePressed

    private void DisplaybtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplaybtnMouseReleased
        // TODO add your handling code here:
        if (displaybtn_over) {
        setHoverColor(Displaybtn);
        } else {
        setResetColor(Displaybtn);
        }
    }//GEN-LAST:event_DisplaybtnMouseReleased
    /////////////////////////////////////////////////////////////////////////
    
    // update btn actions
    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        // TODO add your handling code here:
        setHoverColor(Update);
        updatebtn_over = true;
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        // TODO add your handling code here:
        setResetColor(Update);
        updatebtn_over = false;
    }//GEN-LAST:event_UpdateMouseExited

    private void UpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMousePressed
        // TODO add your handling code here:
        setPressColor(Update);
    }//GEN-LAST:event_UpdateMousePressed

    private void UpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseReleased
        // TODO add your handling code here:
         if (updatebtn_over) {
        setHoverColor(Update);
        } else {
        setResetColor(Update);
        }
    }//GEN-LAST:event_UpdateMouseReleased
    /////////////////////////////////////////////////////////////////////////
    
    // AddEMP btn actions
    private void AddEMPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEMPMouseEntered
        // TODO add your handling code here:
         setHoverColor(AddEMP);
        addempbtn_over = true;
    }//GEN-LAST:event_AddEMPMouseEntered

    private void AddEMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEMPMouseExited
        // TODO add your handling code here:
         setResetColor(AddEMP);
       addempbtn_over = false;
    }//GEN-LAST:event_AddEMPMouseExited

    private void AddEMPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEMPMousePressed
        // TODO add your handling code here:
        setPressColor(AddEMP);
    }//GEN-LAST:event_AddEMPMousePressed

    private void AddEMPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEMPMouseReleased
        // TODO add your handling code here:
           if (addempbtn_over) {
        setHoverColor(AddEMP);
        } else {
        setResetColor(AddEMP);
        }
    }//GEN-LAST:event_AddEMPMouseReleased
    /////////////////////////////////////////////////////////////////////////
    
    // AddTask btn actions
    private void AddTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMouseEntered
        // TODO add your handling code here:
         setHoverColor(AddTask);
        addtaskbtn_over = true;
    }//GEN-LAST:event_AddTaskMouseEntered

    private void AddTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMouseExited
        // TODO add your handling code here:
        setResetColor(AddTask);
       addtaskbtn_over = false;
    }//GEN-LAST:event_AddTaskMouseExited

    private void AddTaskMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMousePressed
        // TODO add your handling code here:
        setPressColor(AddTask);
    }//GEN-LAST:event_AddTaskMousePressed

    private void AddTaskMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMouseReleased
        // TODO add your handling code here:
             if (addtaskbtn_over) {
        setHoverColor(AddTask);
        } else {
        setResetColor(AddTask);
        }
    }//GEN-LAST:event_AddTaskMouseReleased
    /////////////////////////////////////////////////////////////////////////
    
    // approveTask btn actions
    private void approveTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveTaskMouseEntered
        setHoverColor(approveTask);
        approveTask_over = true;
    }//GEN-LAST:event_approveTaskMouseEntered

    private void approveTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveTaskMouseExited
        setResetColor(approveTask);
        approveTask_over = false;
    }//GEN-LAST:event_approveTaskMouseExited

    private void approveTaskMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveTaskMousePressed
        setPressColor(approveTask);
    }//GEN-LAST:event_approveTaskMousePressed

    private void approveTaskMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveTaskMouseReleased
        if (approveTask_over) {
            setHoverColor(approveTask);
        } else {
            setResetColor(approveTask);
        }
    }//GEN-LAST:event_approveTaskMouseReleased

    private void approveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveTaskActionPerformed
        RequestedPostponedTasks requestedPostponedTasks=new RequestedPostponedTasks(); //call new form
        requestedPostponedTasks.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_approveTaskActionPerformed
    /////////////////////////////////////////////////////////////////////////
    
    // login btn actions
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here: Back to login form
        LoginForm Log=new LoginForm(); //call new form
        Log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        setHoverColor(Login);
        loginbtn_over = true;
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        setResetColor(Login);
        loginbtn_over = false;
    }//GEN-LAST:event_LoginMouseExited

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        setPressColor(Login);
    }//GEN-LAST:event_LoginMousePressed

    private void LoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseReleased
        if (loginbtn_over) {
            setHoverColor(Login);
        } else {
            setResetColor(Login);
        }
    }//GEN-LAST:event_LoginMouseReleased
    /////////////////////////////////////////////////////////////////////////
    
    // DeleteEmp btn actions
    private void DeleteEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmpMouseEntered
        setHoverColorDecline(DeleteEmp);
        deletebtn_over = true;
    }//GEN-LAST:event_DeleteEmpMouseEntered

    private void DeleteEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmpMouseExited
        setResetColor(DeleteEmp);
        deletebtn_over = false;
    }//GEN-LAST:event_DeleteEmpMouseExited

    private void DeleteEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmpMousePressed
        setPressColor(DeleteEmp);
    }//GEN-LAST:event_DeleteEmpMousePressed

    private void DeleteEmpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmpMouseReleased
        if (deletebtn_over) {
            setHoverColorDecline(DeleteEmp);
        } else {
            setResetColor(DeleteEmp);
        }
    }//GEN-LAST:event_DeleteEmpMouseReleased

    private void DeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmpActionPerformed
        if(Key==null){  
            JOptionPane.showMessageDialog(this, "Select Employee To Delete","Error",JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/icons/close_30_decline.png")));
        }
        else{
            // insert delete employee function here
            if(!postponedTasksList.isEmpty())
            {
                for(int i=0;i<postponedTasksList.size();i++)
                {
                    if(postponedTasksList.get(i).employeeEmail.equals(Key))
                    {
                        postponedTasksList.remove(i);
                        i--;
                    }
                }
            }
            empsList.get(Key).list.clear();
            empsList.get(Key).Finished_List.clear();
            empsList.remove(Key);
            tblModel.removeRow(row);
            Key=null;
            Name=null;
            row=-1;
            if (postponedTasksList.isEmpty()) {
                approveTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification (1).png")));
                approveTask.setToolTipText(null);
            }
        }
    }//GEN-LAST:event_DeleteEmpActionPerformed
    /////////////////////////////////////////////////////////////////////////
    
    ////////////////////////////////////////// over actions for hover buttons///////////////////////////////////////
    private void setPressColor(javax.swing.JButton b) {
            b.setBackground(new Color(153, 153, 153));
    }
    private void setHoverColor(javax.swing.JButton b) {
            b.setBackground(new Color(102, 102, 102));
    }
    private void setResetColor(javax.swing.JButton b) {
            b.setBackground(new Color(51, 51, 51));
    }
    
    private void setHoverColorConfirm(javax.swing.JButton b) {
        b.setBackground(new Color(0,153,0));
    }
    private void setHoverColorDecline(javax.swing.JButton b) {
        b.setBackground(new Color(153,0,0));
    }
    private boolean displaybtn_over;
    private boolean updatebtn_over;
    private boolean addempbtn_over;
    private boolean addtaskbtn_over;
    private boolean approveTask_over;
    private boolean loginbtn_over;
    private boolean deletebtn_over;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
//       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
                
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEMP;
    private javax.swing.JButton AddTask;
    private javax.swing.JButton DeleteEmp;
    private javax.swing.JPanel Display;
    private javax.swing.JButton Displaybtn;
    private javax.swing.JButton Login;
    private javax.swing.JButton Update;
    private javax.swing.JButton approveTask;
    private javax.swing.JTable data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
